package com.illumina.basespace;

/**
 * Configuration information for a BaseSpace session. These values are necessary to perform
 * authentication and form the URIs necessary to communicate with BaseSpace via REST API
 * @author bking
 *
 */
public interface BaseSpaceConfiguration
{
    /**
     * Get the desired version of BaseSpace to operate against
     * @return the version of BaseSpace 
     */
    public String getVersion();
 
    /**
     * Get the client ID generated by BaseSpace for an application 
     * @return the client id
     */
    public String getClientId();
   
    /**
     * Get the client secret for the client ID 
     * @return the client secret
     */
    public String getClientSecret();
   
    /**
     * Get the root URI for the BaseSpace API
     * @return the API root URI
     */
    public String getApiRootUri();
   
    /**
     * Get the URI fragment for requesting authorization code
     * @return authorization URI
     */
    public String getAuthTokenUriFragment();
    
    /**
     * Get the URI fragment for requesting authorization token
     * @return authorization token URI
     */
    public String getAuthorizationUri();
    
    /**
     * Port for the internal Https server that will receive auth code
     * @return the por
     */
    public int getAuthCodeListenerPort();
}
